---
shares:
  nfs:
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/backups
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/webdav
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/containers/k8s/plex-media
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/backups/proxmox
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/anne
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/coen
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/music
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/music_old
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/music/organized
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/frigate-media
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/home-assistant-config-2
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/immich-media
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/node-red-data
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/paperless-data
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/paperless-export
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/paperless-media
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/protonmail-bridge-data
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/radicale-data
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/transmission-downloads
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/vaultwarden-data
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/ssd/containers/k8s/zwavejs2mqtt-data
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/backups/proxmox/pve-a
      ro: false
      security: []
    - aliases: []
      comment: ""
      enabled: true
      hosts: []
      mapall_group: ""
      mapall_user: ""
      maproot_group: ""
      maproot_user: ""
      networks: []
      path: /mnt/hdd/backups/proxmox/pve-b
      ro: false
      security: []

  iscsi:
    portals:
      - comment: ""
        listen:
          - ip: 0.0.0.0
            port: 3260

    targets:
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: dsmr-reader-db-2
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: home-assistant-db-2
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: immich-database
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: mosquitto-data
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: omada-controller-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: omada-controller-config-2
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: paperless-db
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: prowlarr-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: bazarr-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: sonarr-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: radarr-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: redis
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: uptime-kuma
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: vaultwarden-db-2
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: frigate-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: lidarr-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: jellyfin-cache
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: transmission-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: music-assistant-server-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: jellyseerr-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: jellyfin-config
      - alias:
        auth_networks: []
        groups:
          - auth:
            authmethod: NONE
            initiator:
            portal: 1
        iscsi_parameters:
          QueuedCommands:
        mode: ISCSI
        name: syncthing-config

    extents:
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/bazarr-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: bazarr-config
        path: zvol/ssd/containers/k8s/bazarr-config
        pblocksize: false
        ro: false
        rpm: SSD
        serial: eeca5136c2ab13a
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/dsmr-reader-db-2
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: dsmr-reader-db-2
        path: zvol/ssd/containers/k8s/dsmr-reader-db-2
        pblocksize: false
        ro: false
        rpm: SSD
        serial: f3a6107dbca84bf
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/frigate-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: frigate-config
        path: zvol/ssd/containers/k8s/frigate-config
        pblocksize: false
        ro: false
        rpm: SSD
        serial: 07938a7410ff37e
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/home-assistant-db-2
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: home-assistant-db-2
        path: zvol/ssd/containers/k8s/home-assistant-db-2
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/immich-database
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: immich-database
        path: zvol/ssd/containers/k8s/immich-database
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/jellyfin-cache
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: jellyfin-cache
        path: zvol/ssd/containers/k8s/jellyfin-cache
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/jellyfin-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: jellyfin-config
        path: zvol/ssd/containers/k8s/jellyfin-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/jellyseerr-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: jellyseerr-config
        path: zvol/ssd/containers/k8s/jellyseerr-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/lidarr-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: lidarr-config
        path: zvol/ssd/containers/k8s/lidarr-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/mosquitto-data
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: mosquitto-data
        path: zvol/ssd/containers/k8s/mosquitto-data
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/music-assistant-server-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: music-assistant-server-config
        path: zvol/ssd/containers/k8s/music-assistant-server-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/omada-controller-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: omada-controller-config
        path: zvol/ssd/containers/k8s/omada-controller-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/omada-controller-config-2
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: omada-controller-config-2
        path: zvol/ssd/containers/k8s/omada-controller-config-2
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/paperless-db
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: paperless-db
        path: zvol/ssd/containers/k8s/paperless-db
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/prowlarr-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: prowlarr-config
        path: zvol/ssd/containers/k8s/prowlarr-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/radarr-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: radarr-config
        path: zvol/ssd/containers/k8s/radarr-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/redis
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: redis
        path: zvol/ssd/containers/k8s/redis
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/transmission-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: transmission-config
        path: zvol/ssd/containers/k8s/transmission-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/uptime-kuma
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: uptime-kuma
        path: zvol/ssd/containers/k8s/uptime-kuma
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/vaultwarden-db-2
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: vaultwarden-db-2
        path: zvol/ssd/containers/k8s/vaultwarden-db-2
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/sonarr-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: sonarr-config
        path: zvol/ssd/containers/k8s/sonarr-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
      - avail_threshold: null
        blocksize: 4096
        comment: ""
        disk: zvol/ssd/containers/k8s/syncthing-config
        enabled: true
        filesize: "0"
        insecure_tpc: true
        name: syncthing-config
        path: zvol/ssd/containers/k8s/syncthing-config
        pblocksize: false
        ro: false
        rpm: SSD
        type: DISK
        xen: false
