$ANSIBLE_VAULT;1.1;AES256
38376238303130363333633262613330646562656639613934323736343061383236656637316539
3561323563646262326636613565623335396262623637630a643231383134313465373063396530
34393664333935393131613634393965326637306236386535336264396331303061313136666336
3236366632666134300a653136376134613036626634663635383139353161633265333836326630
33613664323364346261353731393335613365393935366366326135343837626435663330376231
63343065326533313037376130333336633933646536366534343465666261636333643938346235
33393036306339643935323234333730373231316631323537386439376565356233366138623364
31653032306137613833333062346139643634306234653136343031653932663262323561323162
34313664613936306464313833353363323065353339383736643839303261303535333732366431
37383137353737636161373838303630316664633861386238613262356164303861643937656430
65373431336362336134623863333934363066636136303864636335356235313937616232376332
32363838353161343335383466646438663066353165636131336138653065303437323833363332
39646237386337316663616435643063363934613437613231333033313335353265316563383332
33396336663563393338633966353035653537383938633930316561396562303065353566303665
653661313664633438653930323537653034
