---
mount:
  directory: "{{ lookup('env', 'HOME') }}/mnt"
  points:
    - folder: "shared"
      nfs_path: "/mnt/ssd/webdav"
    - folder: "backups"
      nfs_path: "/mnt/ssd/backups"
    - folder: "coen"
      nfs_path: "/mnt/hdd/coen"
    - folder: "anne"
      nfs_path: "/mnt/hdd/anne"
    - folder: "plex-media"
      nfs_path: "/mnt/hdd/containers/k8s/plex-media"
    - folder: "proxmmox-backups"
      nfs_path: "/mnt/hdd/backups/proxmox"
