---
system_timezone: "Europe/Amsterdam"
localdomain: "lan.stamx.nl"

vip_address: "10.0.100.10"

nfs:
  server: "truenas-master.{{ localdomain }}"

ssh:
  authorized_keys:
    public_key:
      control_node_location: "/home/coen/.ssh/ansible.pub"

